FROM alpine:latest

LABEL "repository"="https://github.com/comfuture/actions/writefile"
LABEL "homepage"="https://github.com/comfuture/actions/writefile"
LABEL "maintainer"="Changkyun Kim <comfuture@gmail.com>"

ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
