name: ssh
author: comfuture<comfuture@gmail.com>
description: run ssh command on remote server
branding:
  icon: server
  color: orange
inputs:
  command:
    description: ssh command that you want to run
    required: true
  host:
    description: remote server in `user@server` pattern
    required: true
  port:
    description: ssh port (default=22)
    required: false
    default: '22'
runs:
  using: docker
  image: Dockerfile
