name: Publish to ghpages
author: Changkyun Kim <comfuture@gmail.com>
description: publish files to gh-pages (or given branch name).
branding:
  icon: git-branch
  color: green
inputs:
  build_dir:
    description: path to source directory
    required: true
outputs:
  message_ts:
    description: ts of sent message if available
runs:
  using: docker
  image: Dockerfile