name: Publish to ghpages
author: Changkyun Kim <comfuture@gmail.com>
description: publish files to gh-pages (or given branch name).
branding:
  icon: git-branch
  color: green
inputs:
  github_token:
    description: github token
    required: true
  build_dir:
    description: path to source directory
    default: dist
runs:
  using: composite
  steps:
    - name: run deployment
      shell: bash
      run: entrypoint.sh
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_BUILD_DIR: ${{ inputs.build_dir }}
