FROM alpine/git:v2.32.0

LABEL "maintainer"="Changkyun Kim <comfuture@gmail.com>"
LABEL "repository"="http://github.com/comfuture/actions/ghpages"
LABEL "homepage"="http://github.com/comfuture/actions/ghpages"

ADD entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
