FROM alpine/git

LABEL "maintainer"="Changkyun Kim <comfuture@gmail.com>"
LABEL "repository"="https://github.com/comfuture/actions/ghpages"
LABEL "homepage"="https://github.com/comfuture/actions/ghpages"

ADD entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
