name: slack
author: comfuture<comfuture@gmail.com>
description: Post some message to slack channel
branding:
  icon: mic
  color: purple
inputs:
  channel:
    description: Channel to send to
    required: true
  message:
    description: Message to say
    required: false
  attachments:
    description: additional fields
    required: false
  update:
    description: ts to be updated
    required: false
outputs:
  ts:
    description: Message TS of sent message
runs:
  using: node12
  main: index.js
