FROM node:16-alpine

LABEL repository="https://github.com/comfuture/actions/serverless"
LABEL homepage="https://github.com/comfuture/actions/serverless"
LABEL maintainer="Changkyun Kim"

RUN npm i serverless

ENTRYPOINT [ "serverless" ]
