name: Test ssh action

on:
  push:
    paths:
    - ssh/**
    - .github/workflows/test-ssh-action.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./ssh
      with:
        host: ubuntu@sg.changkyun.kim
        command: ls -al
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
