name: Test rsync action

on:
  push:
    branches:
    - master
    path:
    - rsync/*

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    # simple message
    - uses: ./rsync
      with:
        source: rsync
        dest: comfuture@sg.changkyun.kim:/tmp
      env:
        SSH_KEY: ${{ secrets.DEPLOY_KEY }}
